project:
  type: website
  output-dir: docs

resources:
  - files/key_pic.png


website:
  title: "Miguel Alejandro Sanchez"
  site-url: ""
  repo-url: ""
  description: "Website of Miguel A. Sanchez"
  #cookie-consent: true
  twitter-card: 
    creator: "@mthebreathtaker"  
  search: true
  navbar:
    left:
      - href: files/mas.pdf
        text: CV
      - href: research/index.qmd
        text: Research
  
  page-footer:
    left: |
      {{< fa regular copyright >}} 2023 Miguel A. Sanchez.<br>
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/).<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/malsanchz/malsanchz.github.io)

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: Montserrat
    fontsize: 0.95em
    toc: false

editor: visual